lavalink:
    plugins:
        - dependency: com.dunctebot:skybot-lavalink-plugin:1.7.0
          snapshot: false
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
          snapshot: false
        - dependency: com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0
          snapshot: false
        - dependency: dev.lavalink.youtube:youtube-plugin:1.16.0
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.1
          snapshot: false
        - dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1
          snapshot: false
    pluginsDir: ./plugins
    server:
        bufferDurationMs: 1000
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 10000
        gc-warnings: true
        nonAllocatingFrameBuffer: true
        opusEncodingQuality: 10
        password: Devine
        playerUpdateInterval: 5
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 1000
        useSeekGhosting: true
        youtubeConfig:
            email: godxdev03@gmail.com
            password: rdxhere123
        youtubePlaylistLoadLimit: 15
        youtubeSearchEnabled: true
logging:
    file:
        max-history: 5
        max-size: 10MB
        path: ./logs/
    level:
        com.github.topi314.lavasrc.LavaSrcTools: "OFF"
        com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream: "OFF"
        com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: "OFF"
        com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream: "OFF"
        dev.lavalink.youtube.YoutubeAudioSourceManager: "OFF"
        dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
        lavalink: INFO
        lavalink.server.io.SocketContext: "OFF"
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    dunctebot:
        sources:
            clypit: true
            getyarn: true
            mixcloud: true
            ocremix: true
            pixeldrain: true
            pornhub: true
            reddit: true
            soundgasm: true
            tiktok: true
            tts: true
        ttsLanguage: en-US
    lavalyrics:
        sources:
            - spotify
            - youtube
            - deezer
            - yandexMusic
    lavasrc:
        lyrics-sources:
            deezer: false
            lrcLib: false
            spotify: true
            vkmusic: false
            yandexmusic: false
            youtube: true
        providers:
            - scsearch:%QUERY% - dzisrc:%ISRC% - dzsearch:%QUERY% - ytsearch:"%ISRC%" - ytsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            jiosaavn: false
            qobuz: false
            spotify: true
            tidal: false
            vkmusic: false
            yandexmusic: false
            youtube: true
            ytdlp: false
        spotify:
            albumLoadLimit: 10
            clientId: 85aab1d51a174aad9eed6d7989f530e6
            clientSecret: b2ad05aa725e434c88776a1be8eab6c2
            countryCode: US
            localFiles: false
            playlistLoadLimit: 10
            preferAnonymousToken: true
            resolveArtistsInSearch: true
        youtube:
            countryCode: US
            language: en
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clientOptions:
            ANDROID_MUSIC:
                playback: true
                playlistLoading: false
                searching: true
                videoLoading: true
            ANDROID_VR:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            IOS:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            MUSIC:
                playback: false
                playlistLoading: false
                searching: true
                videoLoading: false
            MWEB:
                playback: false
                playlistLoading: true
                searching: true
                videoLoading: true
            TV:
                playback: true
                playlistLoading: false
                searching: true
                videoLoading: false
            TVHTML5EMBEDDED:
                playback: true
                playlistLoading: false
                searching: true
                videoLoading: true
            WEB:
                playback: false
                playlistLoading: true
                searching: true
                videoLoading: true
            WEBEMBEDDED:
                playback: true
                playlistLoading: false
                searching: true
                videoLoading: true
        clients:
            - TVHTML5EMBEDDED
            - ANDROID_MUSIC
            - IOS
            - TV
            - ANDROID_VR
            - WEB
            - MWEB
            - WEBEMBEDDED
            - MUSIC
        enabled: true
        oauth:
            enabled: false
            refreshToken: 1//01FBgdWG56uUrCgYIARAAGAESNwF-L9Irxxxxxx5-ML2dq0E2zZ6-xxxxxxx
            skipInitialization: true
        playlistLoading: PRIORITIZE
        pot:
            token: ""
        remoteCipher:
            url: https://cipher.kikkia.dev/
            userAgent: Devine
        searching: PRIORITIZE
        videoLoading: FALLBACK
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 25588
